# Generated by Django 5.0.4 on 2024-05-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ontime_completed_orders',
            field=models.IntegerField(default=0),
        ),
    ]
